language: julia

# Homebrew no longer bottles for OSX 10.9; request 10.11
matrix:
  include:
    - os: linux
      julia: 0.4
    - os: linux
      julia: release
    - os: linux
      julia: nightly
    - os: osx
      julia: 0.4
      osx_image: xcode7.3
    - os: osx
      julia: release
      osx_image: xcode7.3
    - os: osx
      julia: nightly
      osx_image: xcode7.3

addons:
  apt_packages:
    - gfortran
    - libgsl0-dev

branches:
  only:
    - master
    - develop

sudo: required

before_install:
  - if [ `uname` == "Linux" ]; then
    unset DYLD_LIBRARY_PATH;
    sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/$(gfortran -dumpversion | cut -f1,2 -d.)/libgfortran.so /usr/local/lib; fi
  - if [ `uname` == "Darwin" ]; then brew install gcc; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -E 'Pkg.clone("https://github.com/JuliaSmoothOptimizers/NLPModels.jl");
    Pkg.checkout("NLPModels", "develop")'

install:
  - julia -e 'versioninfo()'
  - julia -E 'Pkg.clone(pwd());'
  - julia -E 'Pkg.build("CUTEst");'

script:
  - julia --check-bounds=yes -E 'Pkg.test("CUTEst"; coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("CUTEst")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("CUTEst")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
